DROP TABLE IF EXISTS GAME CASCADE;
DROP TABLE IF EXISTS GAME_TILE CASCADE;

CREATE TABLE IF NOT EXISTS GAME(
    GAME_ID SERIAL,
    WIDTH INT DEFAULT 7 NOT NULL,
    HEIGHT INT DEFAULT 7 NOT NULL,
    LINE_TARGET INT DEFAULT 4 NOT NULL,
    CONSTRAINT LINE_TARGET_LTE CHECK(
        LINE_TARGET <= WIDTH
        AND LINE_TARGET <= HEIGHT
    ),
	UNIQUE(GAME_ID,WIDTH,HEIGHT),
	PRIMARY KEY(GAME_ID)
);

CREATE TABLE IF NOT EXISTS GAME_TILE(
	TILE_ID SERIAL,
    GAME_ID SERIAL NOT NULL,
    GAME_WIDTH INT NOT NULL,
    GAME_HEIGHT INT NOT NULL,
	VALUE
    X INT NOT NULL,
    Y INT NOT NULL,
    CONSTRAINT GAME_SIZE CHECK(
        X < GAME_WIDTH AND
        X >= 0
        AND Y < GAME_HEIGHT
        AND Y >= 0
    ),
	FOREIGN KEY (GAME_ID, GAME_WIDTH,GAME_HEIGHT) REFERENCES GAME (GAME_ID, WIDTH,HEIGHT),
	PRIMARY KEY (GAME_ID,X,Y)
);